version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:4
    restart: always
    ports:
      - 6379:6379

  fluentd:
    image: fluent/fluentd:stable
    restart: always
    ports:
      - 24224:24224
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka
    ports:
      - 9092:9092

networks:
  kafka:
