version: '3.1'

services:

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:4
    restart: always
    ports:
      - 6379:6379

  fluentd:
    image: fluent/fluentd:stable
    restart: always
    ports:
      - 24224:24224